version: "3"
services:
    site:
        environment:
            - JEKYLL_ENV=docker
        command: jekyll serve --config  _config.yml,_config-dev.yml
        image: jekyll/jekyll:latest
        volumes:
            - .:/srv/jekyll
        ports:
            - 4000:4000
    build:
        command: jekyll build
        image: jekyll/jekyll:latest
        volumes:
            - .:/srv/jekyll
